"""empty message

Revision ID: 166634e82a63
Revises: 75c3fbbe6d91
Create Date: 2019-10-17 08:36:23.321708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166634e82a63'
down_revision = '75c3fbbe6d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('picture', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
