"""empty message

Revision ID: 2189f3b1e035
Revises: 349423019cd4
Create Date: 2019-10-02 08:56:46.062404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2189f3b1e035'
down_revision = '349423019cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('guest_id', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'guest_id')
    # ### end Alembic commands ###
