"""empty message

Revision ID: 6a4e88d88968
Revises: 2189f3b1e035
Create Date: 2019-10-03 08:46:39.804409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4e88d88968'
down_revision = '2189f3b1e035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_sage', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('last_bump', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_post_last_bump'), 'post', ['last_bump'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_last_bump'), table_name='post')
    op.drop_column('post', 'last_bump')
    op.drop_column('post', 'is_sage')
    # ### end Alembic commands ###
