"""empty message

Revision ID: 75c3fbbe6d91
Revises: a6f486e10b4d
Create Date: 2019-10-04 08:21:14.087026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c3fbbe6d91'
down_revision = 'a6f486e10b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_deleted', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_deleted')
    # ### end Alembic commands ###
