"""empty message

Revision ID: 8c9b3d57e013
Revises: 
Create Date: 2019-10-20 13:29:13.541787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9b3d57e013'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('access_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('OP_num', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('OP_flag', sa.Integer(), nullable=True),
    sa.Column('image_ref', sa.String(length=120), nullable=True),
    sa.Column('thumb_ref', sa.String(length=120), nullable=True),
    sa.Column('board_name', sa.String(length=10), nullable=True),
    sa.Column('answers', sa.String(length=100), nullable=True),
    sa.Column('guest_id', sa.String(length=120), nullable=True),
    sa.Column('is_sage', sa.Integer(), nullable=True),
    sa.Column('last_bump', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_name'], ['board.ref'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_OP_num'), 'post', ['OP_num'], unique=False)
    op.create_index(op.f('ix_post_last_bump'), 'post', ['last_bump'], unique=False)
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_index(op.f('ix_post_last_bump'), table_name='post')
    op.drop_index(op.f('ix_post_OP_num'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('board')
    # ### end Alembic commands ###
