"""empty message

Revision ID: 9d41d1e9a1fc
Revises: 8c9b3d57e013
Create Date: 2019-10-21 10:03:24.389750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d41d1e9a1fc'
down_revision = '8c9b3d57e013'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'description',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('post', 'answers',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('post', 'body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=3000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'body',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)
    op.alter_column('post', 'answers',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('board', 'description',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    ### end Alembic commands ###
